import user from "@/models/user";
import profile from "@/models/profile";
import coupon from "@/models/coupon";
import album from "@/models/album";
import contact from "@/models/contact";
import message from "@/models/message";
import adminMessage from "@/models/adminMessage";
import order from "@/models/order";
import product from "@/models/product";
import transaction from "@/models/transaction";
import withdraw from "@/models/withdraw";
import bank from "@/models/bank";
import groupItem from "@/models/groupItem";
import service from "@/models/service";
import shopProduct from "@/models/shopProduct";
import shopProductImage from "@/models/shopProductImage";
import social from "@/models/social";

export const UserModel = user;
export const ProfileModel = profile;
export const CouponModel = coupon;
export const AlbumModel = album;
export const ContactModel = contact;
export const MessageModel = message;
export const AdminMessageModel = adminMessage;
export const OrderModel = order;
export const ProductModel = product;
export const TransactionModel = transaction;
export const WithdrawModel = withdraw;
export const BankModel = bank;
export const GroupItemModel = groupItem;
export const ServiceModel = service;
export const ShopProductModel = shopProduct;
export const ShopProductImageModel = shopProductImage;
export const SocialModel = social;